name: Trigger auto deployment for car-api-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/car-api-demo-AutoDeployTrigger-c3442fa7-7fe1-4f97-afb0-513696df8db6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CARAPIDEMO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CARAPIDEMO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CARAPIDEMO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: carapiacr.azurecr.io
          registryUsername: ${{ secrets.CARAPIDEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CARAPIDEMO_REGISTRY_PASSWORD }}
          containerAppName: car-api-demo
          resourceGroup: rg-sre-env-03-sweeden
          imageToBuild: carapiacr.azurecr.io/car-api-demo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


